# Generated by Django 5.0.6 on 2024-06-20 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditsale',
            name='has_been_paid',
            field=models.BooleanField(default=False),
        ),
    ]
