# Generated by Django 4.2.13 on 2024-06-21 11:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_creditsale_has_been_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditsale',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='noncreditsale',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
